language: python
python:
    - "3.3"
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install build-essential
    - sudo apt-get install python3-dev
    - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
    - sudo apt-get install libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
    - pip install numpy
before_script:
    #- ls /usr/bin | grep python
    #- ls /usr/include | grep python
    #- ls /usr/include/x86_64-linux-gnu
    #- ls /usr/lib | grep python
    #- ls /usr/lib | grep linux
    #- ls /usr/lib/python3.2 
    #- ls /usr/lib/python3/dist-packages
    #- ls /usr/lib/python3/dist-packages/numpy/core/include
    - git clone https://github.com/Itseez/opencv.git
    - cd opencv
    - git checkout 3.1.0
    - mkdir build
    - cd build
    - export PY3="/home/travis/virtualenv/python3.3.5"
    - cmake -D BUILD_opencv_python3=ON \
      -D PYTHON3_EXECUTABLE=PY3/bin/python3 \
      -D PYTHON3_INCLUDE_DIR=PY3/include/python3.3m \
      -D PYTHON3_LIBRARY=PY3/lib/python3.3 \
      -D PYTHON3_NUMPY_INCLUDE_DIRS=PY3/lib/python3.3/site-packages/numpy/core/include \
      -D PYTHON3_PACKAGES_PATH=PY3/lib/python3.3/site-packages ..
    - make -j8
    - sudo make -j8 install 
    - cd ../..
    - export PYTHONPATH="/usr/local/lib/python3.3"
script:
    - python --version
    - python3 -m unittest tests/main.py
