language: python
python:
    - "3.3"
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install build-essential
    - sudo apt-get install python3-dev python3-numpy
    - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
    - sudo apt-get install libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev # python-dev python-numpy 
before_script:
    - git clone https://github.com/Itseez/opencv.git
    - cd opencv
    - git checkout 3.1.0
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
    - sudo make -j8 install 
    - export PYTHONPATH="lib/python3"
    - cd ../..
script:
    - python3 -m unittest tests/main.py
