language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
before_install:
    - sudo apt-get update
install:
    - sudo apt-get install build-essential
    - sudo apt-get install python3-dev
    - sudo apt-get install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
    - sudo apt-get install libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
    - pip install numpy
before_script:
    - ls /usr/bin | grep python
    - ls /usr/include | grep python
    - ls /usr/lib | grep python
    - git clone https://github.com/Itseez/opencv.git
    - cd opencv
    - git checkout 3.1.0
    - mkdir build
    - cd build
    - cmake -D BUILD_opencv_python3=ON \
      -D PYTHON3_EXECUTABLE=/usr/bin/python3 \
      -D PYTHON3_INCLUDE_DIR=/usr/include/python3 \
      -D PYTHON3_LIBRARY=/usr/lib/python3 \
      -D PYTHON3_NUMPY_INCLUDE_DIRS=/usr/lib/python3/dist-packages/numpy/core/include \
      -D PYTHON3_PACKAGES_PATH=/usr/lib/python3.4/dist-packages ..
    - make -j8
    - sudo make -j8 install 
    - ls lib
    - export PYTHONPATH=$PYTHONPATH:$(pwd)/lib/python3
    - echo 'export PYTHONPATH=$PYTHONPATH:'$(pwd)'/lib/python3' >> ~/virtualenv/python3.2/bin/activate
    - echo 'export PYTHONPATH=$PYTHONPATH:'$(pwd)'/lib/python3' >> ~/virtualenv/python3.3/bin/activate
    - echo 'export PYTHONPATH=$PYTHONPATH:'$(pwd)'/lib/python3' >> ~/virtualenv/python3.4/bin/activate
    - echo 'export PYTHONPATH=$PYTHONPATH:'$(pwd)'/lib/python3' >> ~/virtualenv/python3.5/bin/activate
    - source ~/virtualenv/python3.3/bin/activate
    - cd ../..
script:
    - python -m unittest tests/main.py
